global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using Npgsql.EntityFrameworkCore.PostgreSQL;
global using Microsoft.Extensions.Configuration.Json;
global using Microsoft.Extensions.Configuration;
global using AdressAccounting.Utils;
global using AdressAccounting.Models;
global using AdressAccounting.Services;
global using AdressAccounting.UI;